# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a199f546821d8358308367ed2bfc163c22fb491f4e889ccb72bc86a96f3fbe3a554126723156793323a5621715a5d50ee6d79c73145f6d9f8fe1fc963c44b93a

test:
  secret_key_base: 64e4afb578ee901610e23529daf85c41417ae36967de3d6b09b43d621d43b14292a3bb597d2bd5b7ba3600342b7e86cecfbaeff9349fde6073bfdecc4e87c5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
